name: Auto update JSON

on:
  workflow_dispatch:
  push:
    paths:
      - 'scripts/data.json'

jobs:
  update-tables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run:
          pip install requests

      - name: Run generate script
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
        run: |
          cd scripts
          python update_data.py
          
      - name: Debug ls (check file/folder created)
        run: |
          ls -la
          ls -la scripts/

      - name: Commit & Push if changed (tables/ data.json fresh)
        run: |
          git config --global user.name "poli0981"
          git config --global user.email "127664709+poli0981@users.noreply.github.com"
          git diff --staged --quiet && echo "No changes â€“ skip commit" || (git commit -m "JSON updated [$(date 
          +'%Y-%m-%d')]" && git pull --rebase && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
