name: Automatically Steam F2P Generate Tables

on:
  workflow_run:
    workflows:
      [ 'Auto update JSON' ]
    types: [ completed ]
  workflow_dispatch:

jobs:
  generate:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (with push permission)
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}  # PAT repo scope + workflow, add secret GH_TOKEN

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: run bash script to generate tables
        run: |
          chmod +x ./bash/daily.sh
          ./bash/daily.sh
        shell: bash